import os
import random
import shutil

listaPastas = [
    {"nome":"Normal",
     "sigla":"No-Findings",
     "numero": 0},
    {"nome":"Hollenhorst Emboli",
     "sigla":"Emboli",
     "numero": 1},
    {"nome":"Branch Retinal Artery Occlusion",
     "sigla":"BRAO",
     "numero": 2},
    {"nome":"Cilio-Retinal Artery Occlusion",
     "sigla":"CRAO",
     "numero": 3},
    {"nome":"Branch Retinal Vein Occlusion",
     "sigla":"BRVO",
     "numero": 4},
    {"nome":"Central Retinal Vein Occlusion",
     "sigla":"CRVO",
     "numero": 5},
    {"nome":"Hemi-Central Retinal Vein Occlusion",
     "sigla":"Hemi-CRVO",
     "numero": 6},
    {"nome":"Background Diabetic Retinopathy",
     "sigla":"BDRNPDR",
     "numero": 7},
    {"nome":"Proliferative Diabetic Retinopathy",
     "sigla":"PDR",
     "numero": 8},
    {"nome":"Arteriosclerotic Retinopathy",
     "sigla":"ASR",
     "numero": 9},
    {"nome":"Hypertensive Retinopathy",
     "sigla":"HTR",
     "numero": 10},
    {"nome":"Coat's",
     "sigla":"Coat's",
     "numero": 11},
    {"nome":"Macroaneurism",
     "sigla":"Macroaneurism",
     "numero": 12},
    {"nome":"Choroidal Neovascularization",
     "sigla":"CNV",
     "numero": 13},
    {"nome":"Outros",
     "sigla":"Others",
     "numero": 13},
]

listaPastas2 = [
    {"nome":"Normal",
     "sigla":"normal",
     "numero": 0},
    {"nome":"Emboli",
     "sigla":"emboli",
     "numero": 1},
    {"nome":"Background Diabetic Retinopathy",
     "sigla":"BDRNPDR",
     "numero": 7},
    {"nome":"Outros",
     "sigla":"outros",
     "numero": 14},
]

listaFotos = [
    {"nome": "im0001.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0002.ppm",
     "numeroDoencas": [13, 9]},
    {"nome": "im0003.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0004.ppm",
     "numeroDoencas": [14, 3]},
    {"nome": "im0005.ppm",
     "numeroDoencas": [3, 5]},
    {"nome": "im0006.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0007.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0008.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0009.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0010.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0011.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0012.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0013.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0014.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0015.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0016.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0017.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0018.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0019.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0020.ppm",
     "numeroDoencas": [3, 5]},
    {"nome": "im0021.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0022.ppm",
     "numeroDoencas": [9]},
    {"nome": "im0023.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0024.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0025.ppm",
     "numeroDoencas": [5, 9]},
    {"nome": "im0026.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0027.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0028.ppm",
     "numeroDoencas": [6, 9]},
    {"nome": "im0029.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0030.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0031.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0032.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0033.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0034.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0035.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0036.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0037.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0038.ppm",
     "numeroDoencas": [7, 10]},
    {"nome": "im0039.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0040.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0041.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0042.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0043.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0044.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0045.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0046.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0048.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0049.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0050.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0051.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0052.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0053.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0054.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0055.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0056.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0057.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0058.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0059.ppm",
     "numeroDoencas": [7, 14]},
    {"nome": "im0060.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0061.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0062.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0063.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0064.ppm",
     "numeroDoencas": [12, 1]},
    {"nome": "im0065.ppm",
     "numeroDoencas": [10, 7]},
    {"nome": "im0066.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0067.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0068.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0069.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0070.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0071.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0072.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0073.ppm",
     "numeroDoencas": [10, 9]},
    {"nome": "im0074.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0075.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0076.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0077.ppm",
     "numeroDoencas": [0, 10]},
    {"nome": "im0078.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0079.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0080.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0081.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0082.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0083.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0084.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0085.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0086.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0087.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0088.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0089.ppm",
     "numeroDoencas": [7, 10]},
    {"nome": "im0090.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0091.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0092.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0093.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0094.ppm",
     "numeroDoencas": [7, 10]},
    {"nome": "im0095.ppm",
     "numeroDoencas": [4]},
    {"nome": "im0096.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0097.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0098.ppm",
     "numeroDoencas": [14, 1]},
    {"nome": "im0099.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0100.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0101.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0102.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0103.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0104.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0105.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0106.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0107.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0110.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0111.ppm",
     "numeroDoencas": [7, 14]},
    {"nome": "im0112.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0113.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0114.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0115.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0116.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0117.ppm",
     "numeroDoencas": [7, 9]},
    {"nome": "im0118.ppm",
     "numeroDoencas": [7, 9]},
    {"nome": "im0119.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0120.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0121.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0122.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0123.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0124.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0125.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0126.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0127.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0128.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0129.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0130.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0131.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0132.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0133.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0134.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0135.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0136.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0137.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0138.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0139.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0140.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0141.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0142.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0143.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0145.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0146.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0147.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0148.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0149.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0150.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0151.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0152.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0153.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0154.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0155.ppm",
     "numeroDoencas": [7, 9]},
    {"nome": "im0156.ppm",
     "numeroDoencas": [7, 9]},
    {"nome": "im0157.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0158.ppm",
     "numeroDoencas": [13, 7]},
    {"nome": "im0159.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0160.ppm",
     "numeroDoencas": [5, 9]},
    {"nome": "im0161.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0162.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0163.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0164.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0165.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0166.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0168.ppm",
     "numeroDoencas": [5, 3]},
    {"nome": "im0169.ppm",
     "numeroDoencas": [5, 3]},
    {"nome": "im0170.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0171.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0172.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0173.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0174.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0175.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0176.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0177.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0178.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0179.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0180.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0181.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0182.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0183.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0184.ppm",
     "numeroDoencas": [0, 14]},
    {"nome": "im0185.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0186.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0187.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0188.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0189.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0190.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0191.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0192.ppm",
     "numeroDoencas": [8, 14]},
    {"nome": "im0193.ppm",
     "numeroDoencas": [7, 14]},
    {"nome": "im0194.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0195.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0196.ppm",
     "numeroDoencas": [7, 9]},
    {"nome": "im0197.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0198.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0199.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0200.ppm",
     "numeroDoencas": [4]},
    {"nome": "im0201.ppm",
     "numeroDoencas": [4]},
    {"nome": "im0202.ppm",
     "numeroDoencas": [4]},
    {"nome": "im0203.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0204.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0205.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0206.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0207.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0208.ppm",
     "numeroDoencas": [9]},
    {"nome": "im0209.ppm",
     "numeroDoencas": [4, 9]},
    {"nome": "im0210.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0211.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0212.ppm",
     "numeroDoencas": [14, 1]},
    {"nome": "im0213.ppm",
     "numeroDoencas": [0, 14]},
    {"nome": "im0214.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0215.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0216.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0217.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0218.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0219.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0220.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0221.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0222.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0223.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0224.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0225.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0226.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0227.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0228.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0229.ppm",
     "numeroDoencas": [7, 14]},
    {"nome": "im0230.ppm",
     "numeroDoencas": [7, 9]},
    {"nome": "im0231.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0232.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0233.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0234.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0235.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0236.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0237.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0238.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0239.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0240.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0241.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0242.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0243.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0244.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0245.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0246.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0247.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0248.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0249.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0250.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0251.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0252.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0253.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0254.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0255.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0256.ppm",
     "numeroDoencas": [7, 14]},
    {"nome": "im0257.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0258.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0259.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0260.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0261.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0262.ppm",
     "numeroDoencas": [14, 9]},
    {"nome": "im0263.ppm",
     "numeroDoencas": [14, 9]},
    {"nome": "im0264.ppm",
     "numeroDoencas": [14, 1]},
    {"nome": "im0265.ppm",
     "numeroDoencas": [14, 1]},
    {"nome": "im0266.ppm",
     "numeroDoencas": [14, 1]},
    {"nome": "im0267.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0268.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0269.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0270.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0271.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0272.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0273.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0274.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0275.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0276.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0277.ppm",
     "numeroDoencas": [7]},
    {"nome": "im0278.ppm",
     "numeroDoencas": [0]},
    {"nome": "im0279.ppm",
     "numeroDoencas": [12]},
    {"nome": "im0280.ppm",
     "numeroDoencas": [9]},
    {"nome": "im0281.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0282.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0283.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0284.ppm",
     "numeroDoencas": [9]},
    {"nome": "im0285.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0286.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0287.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0288.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0289.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0290.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0291.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0292.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0293.ppm",
     "numeroDoencas": [9, 10]},
    {"nome": "im0294.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0295.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0296.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0297.ppm",
     "numeroDoencas": [2]},
    {"nome": "im0298.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0299.ppm",
     "numeroDoencas": [2]},
    {"nome": "im0300.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0301.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0302.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0303.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0304.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0305.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0306.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0307.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0308.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0309.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0310.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0311.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0312.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0313.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0314.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0315.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0316.ppm",
     "numeroDoencas": [11]},
    {"nome": "im0317.ppm",
     "numeroDoencas": [1]},
    {"nome": "im0318.ppm",
     "numeroDoencas": [3, 1]},
    {"nome": "im0319.ppm",
     "numeroDoencas": [1]},
    {"nome": "im0320.ppm",
     "numeroDoencas": [3]},
    {"nome": "im0321.ppm",
     "numeroDoencas": [3, 1]},
    {"nome": "im0322.ppm",
     "numeroDoencas": [3, 1]},
    {"nome": "im0323.ppm",
     "numeroDoencas": [1]},
    {"nome": "im0324.ppm",
     "numeroDoencas": [1]},
    {"nome": "im0325.ppm",
     "numeroDoencas": [1]},
    {"nome": "im0326.ppm",
     "numeroDoencas": [2, 1]},
    {"nome": "im0327.ppm",
     "numeroDoencas": [2, 1]},
    {"nome": "im0328.ppm",
     "numeroDoencas": [2, 1]},
    {"nome": "im0329.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0330.ppm",
     "numeroDoencas": [4]},
    {"nome": "im0331.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0332.ppm",
     "numeroDoencas": [6, 10]},
    {"nome": "im0333.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0334.ppm",
     "numeroDoencas": [6, 9]},
    {"nome": "im0335.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0336.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0337.ppm",
     "numeroDoencas": [5]},
    {"nome": "im0338.ppm",
     "numeroDoencas": [4]},
    {"nome": "im0339.ppm",
     "numeroDoencas": [14, 1]},
    {"nome": "im0340.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0341.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0342.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0343.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0344.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0345.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0346.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0347.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0348.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0349.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0350.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0351.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0352.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0353.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0354.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0355.ppm",
     "numeroDoencas": [14, 1]},
    {"nome": "im0356.ppm",
     "numeroDoencas": [8]},
    {"nome": "im0357.ppm",
     "numeroDoencas": [12]},
    {"nome": "im0358.ppm",
     "numeroDoencas": [12]},
    {"nome": "im0359.ppm",
     "numeroDoencas": [12]},
    {"nome": "im0360.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0361.ppm",
     "numeroDoencas": [12, 1]},
    {"nome": "im0362.ppm",
     "numeroDoencas": [12]},
    {"nome": "im0363.ppm",
     "numeroDoencas": [12]},
    {"nome": "im0364.ppm",
     "numeroDoencas": [4, 9]},
    {"nome": "im0365.ppm",
     "numeroDoencas": [4]},
    {"nome": "im0366.ppm",
     "numeroDoencas": [4, 9]},
    {"nome": "im0367.ppm",
     "numeroDoencas": [4]},
    {"nome": "im0368.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0369.ppm",
     "numeroDoencas": [6]},
    {"nome": "im0370.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0371.ppm",
     "numeroDoencas": [13]},
    {"nome": "im0372.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0373.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0374.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0375.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0376.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0377.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0378.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0379.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0380.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0381.ppm",
     "numeroDoencas": [13, 9]},
    {"nome": "im0382.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0383.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0384.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0385.ppm",
     "numeroDoencas": [13, 1]},
    {"nome": "im0395.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0396.ppm",
     "numeroDoencas": [10, 9]},
    {"nome": "im0397.ppm",
     "numeroDoencas": [10]},
    {"nome": "im0398.ppm",
     "numeroDoencas": [10, 9]},
    {"nome": "im0399.ppm",
     "numeroDoencas": [2, 1]},
    {"nome": "im0400.ppm",
     "numeroDoencas": [2, 1]},
    {"nome": "im0401.ppm",
     "numeroDoencas": [14]},
    {"nome": "im0402.ppm",
     "numeroDoencas": [14]},
]

random.shuffle(listaFotos)
setenta_porcento = int(len(listaFotos)*0.70)
vinte_porcento = int(len(listaFotos)*0.20)
listaFotos_train = listaFotos[0:setenta_porcento]
listaFotos_test = listaFotos[setenta_porcento:]
listaFotos_val = listaFotos[(len(listaFotos)-setenta_porcento):]
source_dir = "all-images"

folder_name_train = "train"
folder_name_test = "test"
folder_name_val = "val"
os.makedirs(folder_name_train, exist_ok=True)
os.makedirs(folder_name_test, exist_ok=True)
os.makedirs(folder_name_val, exist_ok=True)

for pasta in listaPastas2:
    folder_name = f"{pasta['sigla']}"
    folder_path = os.path.join(folder_name_train, folder_name)
    os.makedirs(folder_path, exist_ok=True)
for pasta in listaPastas2:
    folder_name = f"{pasta['sigla']}"
    folder_path = os.path.join(folder_name_test, folder_name)
    os.makedirs(folder_path, exist_ok=True)
for pasta in listaPastas2:
    folder_name = f"{pasta['sigla']}"
    folder_path = os.path.join(folder_name_val, folder_name)
    os.makedirs(folder_path, exist_ok=True)

for foto in listaFotos_train:
    src_file = os.path.join(source_dir, foto["nome"])
    for pasta in listaPastas2:
        if any(doenca in [pasta["numero"]] for doenca in foto["numeroDoencas"]):
            dest_folder = f'{pasta["sigla"]}'
            dest_path = os.path.join(folder_name_train, dest_folder)
            shutil.copy2(src_file, dest_path)
            break
for foto in listaFotos_test:
    src_file = os.path.join(source_dir, foto["nome"])
    for pasta in listaPastas2:
        if any(doenca in [pasta["numero"]] for doenca in foto["numeroDoencas"]):
            dest_folder = f'{pasta["sigla"]}'
            dest_path = os.path.join(folder_name_test, dest_folder)
            shutil.copy2(src_file, dest_path)
            break
for pasta in listaPastas2:
    src_file = os.path.join(source_dir, foto["nome"])
    if any(doenca in [pasta["numero"]] for doenca in foto["numeroDoencas"]):
        dest_folder = f'{pasta["sigla"]}'
        dest_path = os.path.join(folder_name_val, dest_folder)
        shutil.copy2(src_file, dest_path)
        break